import { AuthUserProvider } from "../../../firebase/Auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthUserProvider>{children}</AuthUserProvider>
      </body>
    </html>
  );
}
